language: ruby
notifications:
  email: false
rvm:
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rake db:migrate db:seed db:test:prepare ci

after_success:
  #chmod 600 deployment/key.pem
  #ssh-add deployment/key.pem
  - gem install capistrano
  - cap deploy