development:
  admin_pids: ["PID000242802", "abwe-pid" , "dgj-pid", "krv-pid", "jatr-pid"]

test:
  admin_pids: ["PID000242802", "abwe-pid" , "dgj-pid", "krv-pid", "jatr-pid", "spec-admin-pid"]

production:
  admin_pids: ["krv-pid"]
