development:
  admin_pids: ["PID000242802", "PID000378112" , "PID000282354", "krv-pid"]

test:
  admin_pids: ["PID000242802", "PID000378112" , "PID000282354", "krv-pid", "spec-admin-pid"]

production:
  admin_pids: ["krv-pid"]
